export interface FabricDetail {
  sourceSheet: string;
  pattern: string;
  styleId: string;
  option: string;
  fabricCode: string;
  supplier: string;
  construction: string;
  content: string;
  widthInch: string;
  weightGm2: string;
  priceYd: string;
  priceLb: string;
  finish: string;
  yarnDetail: string;
  comment: string;
  fabricCountry: string;
  originalText: string;
}

export const FABRIC_DETAIL_ROWS = [
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW271TALMJK022",
    "styleId": "HDW127271",
    "option": "",
    "fabricCode": "FL25102386",
    "supplier": "",
    "construction": "2*2 Rib (hudson rib)",
    "content": "",
    "widthInch": "",
    "weightGm2": "",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\ud68c\uc0ac \uc2dc\uc2a4\ud15c \ub4f1\ub85d (hudson rib)",
    "fabricCountry": "",
    "originalText": "FL25102386 (hudson rib)"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALMJK010",
    "styleId": "HDW227013",
    "option": "opt1",
    "fabricCode": "FL25102386",
    "supplier": "",
    "construction": "2*2 Rib (hudson rib)",
    "content": "",
    "widthInch": "",
    "weightGm2": "",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\ud68c\uc0ac \uc2dc\uc2a4\ud15c \ub4f1\ub85d (hudson rib)",
    "fabricCountry": "",
    "originalText": "Option 1 -FL25102386 (hudson rib)"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALMJK010",
    "styleId": "HDW227020",
    "option": "opt2",
    "fabricCode": "FL25122688",
    "supplier": "Yourui",
    "construction": "Wide Rib",
    "content": "56/38/6 Cotton/Polyester/Spandex",
    "widthInch": "49/51",
    "weightGm2": "235",
    "priceYd": "2.08",
    "priceLb": "3.4",
    "finish": "",
    "yarnDetail": "BCI CO/RCP32'S + SP30D",
    "comment": "Old Navy BULK QTY",
    "fabricCountry": "China",
    "originalText": "Option 2 - FL25122688"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALMJK011",
    "styleId": "HDW227091",
    "option": "",
    "fabricCode": "FL25122642",
    "supplier": "YISHENG",
    "construction": "2*2 Rib",
    "content": "57/38/5 Cotton/Polyester/Spandex",
    "widthInch": "55/57",
    "weightGm2": "240",
    "priceYd": "3.31",
    "priceLb": "4.74",
    "finish": "",
    "yarnDetail": "",
    "comment": "MOQ/MCQ 4000/2000 YD, LT 30D",
    "fabricCountry": "China",
    "originalText": "FL25122642"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALMJK013",
    "styleId": "HDW227092",
    "option": "",
    "fabricCode": "FL25122642",
    "supplier": "YISHENG",
    "construction": "2*2 Rib",
    "content": "57/38/5 Cotton/Polyester/Spandex",
    "widthInch": "55/57",
    "weightGm2": "240",
    "priceYd": "3.31",
    "priceLb": "4.74",
    "finish": "",
    "yarnDetail": "",
    "comment": "MOQ/MCQ 4000/2000 YD, LT 30D",
    "fabricCountry": "China",
    "originalText": "FL25122642"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALNYK018",
    "styleId": "HDW227031",
    "option": "",
    "fabricCode": "WL0113-21",
    "supplier": "",
    "construction": "",
    "content": "100% COTTON",
    "widthInch": "",
    "weightGm2": "150",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\uc678\ubd80 \uc6d0\ub2e8 (FL # \ubbf8\ubc1c\uae09)",
    "fabricCountry": "",
    "originalText": "WL0113-21  ,100% COTTON , 150GSM"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALNYK015",
    "styleId": "HDW227096",
    "option": "",
    "fabricCode": "WL0113-21",
    "supplier": "",
    "construction": "",
    "content": "100% COTTON",
    "widthInch": "",
    "weightGm2": "150",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\uc678\ubd80 \uc6d0\ub2e8 (FL # \ubbf8\ubc1c\uae09)",
    "fabricCountry": "",
    "originalText": "WL0113-21  ,100% COTTON , 150GSM"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW271KSNNYK002",
    "styleId": "HDW127270",
    "option": "",
    "fabricCode": "WL0113-21",
    "supplier": "",
    "construction": "",
    "content": "100% COTTON",
    "widthInch": "",
    "weightGm2": "150",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\uc678\ubd80 \uc6d0\ub2e8 (FL # \ubbf8\ubc1c\uae09)",
    "fabricCountry": "",
    "originalText": "WL0113-21  ,100% COTTON , 150GSM"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALNYK008",
    "styleId": "HDW227023",
    "option": "opt1",
    "fabricCode": "SS-C-10506-1",
    "supplier": "",
    "construction": "",
    "content": "55/45 LINEN/POLY",
    "widthInch": "",
    "weightGm2": "210",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\uc678\ubd80 \uc6d0\ub2e8 (FL # \ubbf8\ubc1c\uae09)",
    "fabricCountry": "",
    "originalText": "1. SS-C-10506-1 (55/45 LINEN /POLY, 210GSM)"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALNYK008",
    "styleId": "HDW227024",
    "option": "opt2",
    "fabricCode": "HS-1027-H",
    "supplier": "",
    "construction": "Slub",
    "content": "60/40 COTTON/SLUB",
    "widthInch": "",
    "weightGm2": "180",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\uc678\ubd80 \uc6d0\ub2e8 (FL # \ubbf8\ubc1c\uae09)",
    "fabricCountry": "",
    "originalText": "2. HS-1027-H (60/40 COTTON/SLUB ,180GSM)"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALNYK008",
    "styleId": "HDW227138",
    "option": "opt3",
    "fabricCode": "",
    "supplier": "",
    "construction": "",
    "content": "",
    "widthInch": "",
    "weightGm2": "",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "",
    "fabricCountry": "",
    "originalText": ""
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALNYK009",
    "styleId": "HDW227025",
    "option": "opt1",
    "fabricCode": "SS-C-10506-1",
    "supplier": "",
    "construction": "",
    "content": "55/45 LINEN/POLY",
    "widthInch": "",
    "weightGm2": "210",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\uc678\ubd80 \uc6d0\ub2e8 (FL # \ubbf8\ubc1c\uae09)",
    "fabricCountry": "",
    "originalText": "1. SS-C-10506-1 (55/45 LINEN /POLY, 210GSM)"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALNYK009",
    "styleId": "HDW227026",
    "option": "opt2",
    "fabricCode": "HS-1027-H",
    "supplier": "",
    "construction": "Slub",
    "content": "60/40 COTTON/SLUB",
    "widthInch": "",
    "weightGm2": "180",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\uc678\ubd80 \uc6d0\ub2e8 (FL # \ubbf8\ubc1c\uae09)",
    "fabricCountry": "",
    "originalText": "2. HS-1027-H (60/40 COTTON/SLUB ,180GSM)"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALNYK009",
    "styleId": "HDW227139",
    "option": "opt3",
    "fabricCode": "",
    "supplier": "",
    "construction": "",
    "content": "",
    "widthInch": "",
    "weightGm2": "",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "",
    "fabricCountry": "",
    "originalText": ""
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALMJK012",
    "styleId": "HDW227021",
    "option": "",
    "fabricCode": "FL25102386",
    "supplier": "",
    "construction": "2*2 Rib (hudson rib)",
    "content": "",
    "widthInch": "",
    "weightGm2": "",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\ud68c\uc0ac \uc2dc\uc2a4\ud15c \ub4f1\ub85d (hudson rib)",
    "fabricCountry": "",
    "originalText": "FL25102386 (hudson rib)"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALMJK014",
    "styleId": "HDW227076",
    "option": "",
    "fabricCode": "FL25102386",
    "supplier": "",
    "construction": "2*2 Rib (hudson rib)",
    "content": "",
    "widthInch": "",
    "weightGm2": "",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\ud68c\uc0ac \uc2dc\uc2a4\ud15c \ub4f1\ub85d (hudson rib)",
    "fabricCountry": "",
    "originalText": "FL25102386 (hudson rib)"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALNYK010",
    "styleId": "HDW227097",
    "option": "opt1",
    "fabricCode": "CLEAN JSY (WL0113-21)",
    "supplier": "",
    "construction": "Single Jersey",
    "content": "100% COTTON",
    "widthInch": "",
    "weightGm2": "150",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\uc678\ubd80 \uc6d0\ub2e8 (FL # \ubbf8\ubc1c\uae09)",
    "fabricCountry": "",
    "originalText": "OPT1-CLEAN JSY (WL0113-21  ,100% COTTON , 150GSM)"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALNYK010",
    "styleId": "HDW227098",
    "option": "opt2",
    "fabricCode": "CMS BULK",
    "supplier": "",
    "construction": "",
    "content": "",
    "widthInch": "",
    "weightGm2": "",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\uc678\ubd80 \uc6d0\ub2e8 (FL # \ubbf8\ubc1c\uae09)",
    "fabricCountry": "",
    "originalText": "OPT2-CMS BULK"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALMJK009",
    "styleId": "HDW227012",
    "option": "opt1",
    "fabricCode": "FL25102386",
    "supplier": "",
    "construction": "2*2 Rib (hudson rib)",
    "content": "",
    "widthInch": "",
    "weightGm2": "",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\ud68c\uc0ac \uc2dc\uc2a4\ud15c \ub4f1\ub85d (hudson rib)",
    "fabricCountry": "",
    "originalText": "FL25102386 (hudson rib)"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALMJK009",
    "styleId": "HDW227019",
    "option": "opt2",
    "fabricCode": "FL25102386",
    "supplier": "",
    "construction": "2*2 Rib (hudson rib)",
    "content": "",
    "widthInch": "",
    "weightGm2": "",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\ud68c\uc0ac \uc2dc\uc2a4\ud15c \ub4f1\ub85d (hudson rib)",
    "fabricCountry": "",
    "originalText": "FL25102386 (hudson rib)"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALMJK018",
    "styleId": "HDW227015",
    "option": "",
    "fabricCode": "FL25072586",
    "supplier": "DANOE",
    "construction": "Single Jacquard",
    "content": "91/8/1 Cotton/Polyester/Spandex",
    "widthInch": "47/49",
    "weightGm2": "225",
    "priceYd": "3.45",
    "priceLb": "6.12",
    "finish": "",
    "yarnDetail": "32'S/1 + SPAN 75D",
    "comment": "MOQ/MCQ 3,000/1,500Y",
    "fabricCountry": "China",
    "originalText": "FL25072586"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALMJK019",
    "styleId": "HDW227016",
    "option": "",
    "fabricCode": "FL25072586",
    "supplier": "DANOE",
    "construction": "Single Jacquard",
    "content": "91/8/1 Cotton/Polyester/Spandex",
    "widthInch": "47/49",
    "weightGm2": "225",
    "priceYd": "3.45",
    "priceLb": "6.12",
    "finish": "",
    "yarnDetail": "32'S/1 + SPAN 75D",
    "comment": "MOQ/MCQ 3,000/1,500Y",
    "fabricCountry": "China",
    "originalText": "FL25072586"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALMJK015",
    "styleId": "HDW227057",
    "option": "",
    "fabricCode": "SS-C-10506-1",
    "supplier": "",
    "construction": "",
    "content": "55/45 LINEN/POLY",
    "widthInch": "",
    "weightGm2": "210",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\uc678\ubd80 \uc6d0\ub2e8 (FL # \ubbf8\ubc1c\uae09)",
    "fabricCountry": "",
    "originalText": "SS-C-10506-1 (55/45 LINEN /POLY, 210GSM)"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALNYK004",
    "styleId": "HDW227033",
    "option": "",
    "fabricCode": "SS-C-10506-1",
    "supplier": "",
    "construction": "",
    "content": "55/45 LINEN/POLY",
    "widthInch": "",
    "weightGm2": "210",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\uc678\ubd80 \uc6d0\ub2e8 (FL # \ubbf8\ubc1c\uae09)",
    "fabricCountry": "",
    "originalText": "SS-C-10506-1 (55/45 LINEN /POLY, 210GSM)"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALNYK004",
    "styleId": "HDW227106",
    "option": "",
    "fabricCode": "FL20032063",
    "supplier": "",
    "construction": "",
    "content": "",
    "widthInch": "",
    "weightGm2": "",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\ud68c\uc0ac \uc2dc\uc2a4\ud15c \ub4f1\ub85d (\uc6cc\ud06c\ubd81 \ub9c8\uc2a4\ud130 \uc678\ubd80)",
    "fabricCountry": "",
    "originalText": "FL20032063 (SLUB JERSEY) , 100% CTTN, 190GSM"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALNYK017",
    "styleId": "HDW227060",
    "option": "",
    "fabricCode": "SS-C-10506-1",
    "supplier": "",
    "construction": "",
    "content": "55/45 LINEN/POLY",
    "widthInch": "",
    "weightGm2": "210",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\uc678\ubd80 \uc6d0\ub2e8 (FL # \ubbf8\ubc1c\uae09)",
    "fabricCountry": "",
    "originalText": "SS-C-10506-1 (55/45 LINEN /POLY, 210GSM)"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALNYK021",
    "styleId": "HDW227014",
    "option": "",
    "fabricCode": "SS-C-10506-1",
    "supplier": "",
    "construction": "",
    "content": "55/45 LINEN/POLY",
    "widthInch": "",
    "weightGm2": "210",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\uc678\ubd80 \uc6d0\ub2e8 (FL # \ubbf8\ubc1c\uae09)",
    "fabricCountry": "",
    "originalText": "SS-C-10506-1 (55/45 LINEN /POLY, 210GSM)"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALMJK016",
    "styleId": "HDW227058",
    "option": "",
    "fabricCode": "FL26012391",
    "supplier": "XINSHENG",
    "construction": "Single Jacquard",
    "content": "54/37/9 Cotton/Polyester/Spandex",
    "widthInch": "59/61",
    "weightGm2": "188",
    "priceYd": "2.36",
    "priceLb": "4.03",
    "finish": "",
    "yarnDetail": "40'S + 50'S + 100D",
    "comment": "MOQ/MCQ 5K/3K yd, LT 45D",
    "fabricCountry": "China",
    "originalText": "FL26012391"
  },
  {
    "sourceSheet": "KNIT TOP",
    "pattern": "PW272TALMJK017",
    "styleId": "HDW227059",
    "option": "",
    "fabricCode": "FL26012391",
    "supplier": "XINSHENG",
    "construction": "Single Jacquard",
    "content": "54/37/9 Cotton/Polyester/Spandex",
    "widthInch": "59/61",
    "weightGm2": "188",
    "priceYd": "2.36",
    "priceLb": "4.03",
    "finish": "",
    "yarnDetail": "40'S + 50'S + 100D",
    "comment": "MOQ/MCQ 5K/3K yd, LT 45D",
    "fabricCountry": "China",
    "originalText": "FL26012391"
  },
  {
    "sourceSheet": "T BY TALBOTS",
    "pattern": "PW272TALMJK022",
    "styleId": "HDW227140",
    "option": "",
    "fabricCode": "FL26032349",
    "supplier": "FLY J",
    "construction": "2*2 Rib",
    "content": "50/45/5 Modal/Cotton/Spandex",
    "widthInch": "57/59",
    "weightGm2": "270",
    "priceYd": "2.62",
    "priceLb": "3.21",
    "finish": "",
    "yarnDetail": "40S+40D SP",
    "comment": "MOQ/MCQ 4,950/1,250yd LT 30-40D",
    "fabricCountry": "China",
    "originalText": "FL26032349"
  },
  {
    "sourceSheet": "T BY TALBOTS",
    "pattern": "PW272TALMJK020",
    "styleId": "HDW227018",
    "option": "",
    "fabricCode": "FL26032349",
    "supplier": "FLY J",
    "construction": "2*2 Rib",
    "content": "50/45/5 Modal/Cotton/Spandex",
    "widthInch": "57/59",
    "weightGm2": "270",
    "priceYd": "2.62",
    "priceLb": "3.21",
    "finish": "",
    "yarnDetail": "40S+40D SP",
    "comment": "MOQ/MCQ 4,950/1,250yd LT 30-40D",
    "fabricCountry": "China",
    "originalText": "FL26032349"
  },
  {
    "sourceSheet": "T BY TALBOTS",
    "pattern": "PW272TALNYK022",
    "styleId": "HDW227134",
    "option": "opt1",
    "fabricCode": "FL26032296",
    "supplier": "REALEVER",
    "construction": "Single Jersey",
    "content": "73/18/9 Polyester/Tencel/Spandex",
    "widthInch": "61/63",
    "weightGm2": "210",
    "priceYd": "3.5",
    "priceLb": "5.18",
    "finish": "",
    "yarnDetail": "50S+SP 40D",
    "comment": "MOQ/MCQ 3K/1K LT 50D",
    "fabricCountry": "China",
    "originalText": "option1/ FL26032296                       Option 2/ FL24052040"
  },
  {
    "sourceSheet": "T BY TALBOTS",
    "pattern": "PW272TALNYK022",
    "styleId": "HDW227135",
    "option": "opt2",
    "fabricCode": "FL24052040",
    "supplier": "",
    "construction": "",
    "content": "",
    "widthInch": "",
    "weightGm2": "",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\ud68c\uc0ac \uc2dc\uc2a4\ud15c \ub4f1\ub85d (\uc6cc\ud06c\ubd81 \ub9c8\uc2a4\ud130 \uc678\ubd80)",
    "fabricCountry": "",
    "originalText": "Option 2/ FL24052040"
  },
  {
    "sourceSheet": "T BY TALBOTS",
    "pattern": "PW272TALNYK023",
    "styleId": "HDW227136",
    "option": "opt1",
    "fabricCode": "FL26032296",
    "supplier": "REALEVER",
    "construction": "Single Jersey",
    "content": "73/18/9 Polyester/Tencel/Spandex",
    "widthInch": "61/63",
    "weightGm2": "210",
    "priceYd": "3.5",
    "priceLb": "5.18",
    "finish": "",
    "yarnDetail": "50S+SP 40D",
    "comment": "MOQ/MCQ 3K/1K LT 50D",
    "fabricCountry": "China",
    "originalText": "option1/ FL26032296                       Option 2/ FL24052040"
  },
  {
    "sourceSheet": "T BY TALBOTS",
    "pattern": "PW272TALNYK023",
    "styleId": "HDW227137",
    "option": "opt2",
    "fabricCode": "FL24052040",
    "supplier": "",
    "construction": "",
    "content": "",
    "widthInch": "",
    "weightGm2": "",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\ud68c\uc0ac \uc2dc\uc2a4\ud15c \ub4f1\ub85d (\uc6cc\ud06c\ubd81 \ub9c8\uc2a4\ud130 \uc678\ubd80)",
    "fabricCountry": "",
    "originalText": "Option 2/ FL24052040"
  },
  {
    "sourceSheet": "T BY TALBOTS",
    "pattern": "PW272TALNYK020",
    "styleId": "HDW227061",
    "option": "",
    "fabricCode": "FL25092390",
    "supplier": "FYNEX",
    "construction": "Interlock",
    "content": "71/29 Nylon/Spandex",
    "widthInch": "58/60",
    "weightGm2": "137",
    "priceYd": "2.94",
    "priceLb": "7.03",
    "finish": "",
    "yarnDetail": "20DNYL+20DSPX",
    "comment": "6000YD/1000YD",
    "fabricCountry": "China",
    "originalText": "FL25092390"
  },
  {
    "sourceSheet": "T BY TALBOTS",
    "pattern": "PW272TALNYK024",
    "styleId": "HDW227067",
    "option": "",
    "fabricCode": "FL25092390",
    "supplier": "FYNEX",
    "construction": "Interlock",
    "content": "71/29 Nylon/Spandex",
    "widthInch": "58/60",
    "weightGm2": "137",
    "priceYd": "2.94",
    "priceLb": "7.03",
    "finish": "",
    "yarnDetail": "20DNYL+20DSPX",
    "comment": "6000YD/1000YD",
    "fabricCountry": "China",
    "originalText": "FL25092390"
  },
  {
    "sourceSheet": "T BY TALBOTS",
    "pattern": "PA273AMWJEY006",
    "styleId": "HDW227075",
    "option": "",
    "fabricCode": "FL25092390",
    "supplier": "FYNEX",
    "construction": "Interlock",
    "content": "71/29 Nylon/Spandex",
    "widthInch": "58/60",
    "weightGm2": "137",
    "priceYd": "2.94",
    "priceLb": "7.03",
    "finish": "",
    "yarnDetail": "20DNYL+20DSPX",
    "comment": "6000YD/1000YD",
    "fabricCountry": "China",
    "originalText": "FL25092390"
  },
  {
    "sourceSheet": "T BY TALBOTS",
    "pattern": "PW272TALMJK023",
    "styleId": "HDW227151",
    "option": "opt1",
    "fabricCode": "FL25122228",
    "supplier": "GIOVANNI",
    "construction": "Ottoman",
    "content": "100 Cotton",
    "widthInch": "55/57",
    "weightGm2": "250",
    "priceYd": "2.88",
    "priceLb": "3.95",
    "finish": "",
    "yarnDetail": "32S",
    "comment": "MOQ/MCQ 3K/1.5K",
    "fabricCountry": "China",
    "originalText": "OPT1- FL25122228"
  },
  {
    "sourceSheet": "T BY TALBOTS",
    "pattern": "PW272TALMJK023",
    "styleId": "HDW227152",
    "option": "opt2",
    "fabricCode": "FL25032328",
    "supplier": "",
    "construction": "",
    "content": "",
    "widthInch": "",
    "weightGm2": "",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\ud68c\uc0ac \uc2dc\uc2a4\ud15c \ub4f1\ub85d (\uc6cc\ud06c\ubd81 \ub9c8\uc2a4\ud130 \uc678\ubd80)",
    "fabricCountry": "",
    "originalText": "OPT2-FL25032328"
  },
  {
    "sourceSheet": "T BY TALBOTS",
    "pattern": "PW272TALMJK026",
    "styleId": "HDW227037",
    "option": "opt1",
    "fabricCode": "FL25122228",
    "supplier": "GIOVANNI",
    "construction": "Ottoman",
    "content": "100 Cotton",
    "widthInch": "55/57",
    "weightGm2": "250",
    "priceYd": "2.88",
    "priceLb": "3.95",
    "finish": "",
    "yarnDetail": "32S",
    "comment": "MOQ/MCQ 3K/1.5K",
    "fabricCountry": "China",
    "originalText": "OPT1- FL25122228"
  },
  {
    "sourceSheet": "T BY TALBOTS",
    "pattern": "PW272TALMJK026",
    "styleId": "HDW227068",
    "option": "opt2",
    "fabricCode": "YH65140-2",
    "supplier": "",
    "construction": "",
    "content": "",
    "widthInch": "",
    "weightGm2": "",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\uc678\ubd80 \uc6d0\ub2e8 (FL # \ubbf8\ubc1c\uae09)",
    "fabricCountry": "",
    "originalText": "OPT2-YH65140-2"
  },
  {
    "sourceSheet": "T BY TALBOTS",
    "pattern": "PW272TALMJK024",
    "styleId": "HDW227141",
    "option": "",
    "fabricCode": "FL25122228",
    "supplier": "GIOVANNI",
    "construction": "Ottoman",
    "content": "100 Cotton",
    "widthInch": "55/57",
    "weightGm2": "250",
    "priceYd": "2.88",
    "priceLb": "3.95",
    "finish": "",
    "yarnDetail": "32S",
    "comment": "MOQ/MCQ 3K/1.5K",
    "fabricCountry": "China",
    "originalText": "FL25122228"
  },
  {
    "sourceSheet": "T BY TALBOTS",
    "pattern": "PW272TALNYK025",
    "styleId": "HDW227069",
    "option": "opt2",
    "fabricCode": "JTS12705",
    "supplier": "",
    "construction": "",
    "content": "48/47/5 POLY/RAYON/SPAN",
    "widthInch": "",
    "weightGm2": "280",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\uc678\ubd80 \uc6d0\ub2e8 (FL # \ubbf8\ubc1c\uae09)",
    "fabricCountry": "",
    "originalText": "OPT2-JTS12705 (48/47/5 POLY/RAYON/SPAN 280GSM)"
  },
  {
    "sourceSheet": "T BY TALBOTS",
    "pattern": "PW272TALNYK026",
    "styleId": "HDW227071",
    "option": "opt1",
    "fabricCode": "FL25052380",
    "supplier": "yourui",
    "construction": "Scuba",
    "content": "77/17/6 Cotton/Polyester/Spandex",
    "widthInch": "63/65",
    "weightGm2": "280",
    "priceYd": "3.28",
    "priceLb": "3.53",
    "finish": "",
    "yarnDetail": "C50'S/1 + PE50DDTY + SP30D",
    "comment": "MOQ/MCQ 4K/1K YD, LT 15/50D",
    "fabricCountry": "China",
    "originalText": "OPT1- FL25052380"
  },
  {
    "sourceSheet": "T BY TALBOTS",
    "pattern": "PW272TALNYK026",
    "styleId": "HDW227070",
    "option": "opt2",
    "fabricCode": "JTS12705",
    "supplier": "",
    "construction": "",
    "content": "48/47/5 POLY/RAYON/SPAN",
    "widthInch": "",
    "weightGm2": "280",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\uc678\ubd80 \uc6d0\ub2e8 (FL # \ubbf8\ubc1c\uae09)",
    "fabricCountry": "",
    "originalText": "OPT2-JTS12705 (48/47/5 POLY/RAYON/SPAN 280GSM)"
  },
  {
    "sourceSheet": "T BY TALBOTS",
    "pattern": "PW272TALMJK027",
    "styleId": "HDW227149",
    "option": "",
    "fabricCode": "FL25052380",
    "supplier": "yourui",
    "construction": "Scuba",
    "content": "77/17/6 Cotton/Polyester/Spandex",
    "widthInch": "63/65",
    "weightGm2": "280",
    "priceYd": "3.28",
    "priceLb": "3.53",
    "finish": "",
    "yarnDetail": "C50'S/1 + PE50DDTY + SP30D",
    "comment": "MOQ/MCQ 4K/1K YD, LT 15/50D",
    "fabricCountry": "China",
    "originalText": "FL25052380"
  },
  {
    "sourceSheet": "T BY TALBOTS",
    "pattern": "PW272TALMJK025",
    "styleId": "HDW227079",
    "option": "",
    "fabricCode": "JTS-12684-1",
    "supplier": "",
    "construction": "",
    "content": "50/45/5 RAYON/POLY/SPAN",
    "widthInch": "",
    "weightGm2": "285",
    "priceYd": "",
    "priceLb": "",
    "finish": "",
    "yarnDetail": "",
    "comment": "\uc678\ubd80 \uc6d0\ub2e8 (FL # \ubbf8\ubc1c\uae09)",
    "fabricCountry": "",
    "originalText": "JTS-12684-1 (50/45/5 RAYON/POLY/SPAN285GSM)"
  }
] satisfies FabricDetail[];

interface FabricDetailsResponse {
  rows?: FabricDetail[];
}

export function getFabricDetailsForStyle(styleId: string): FabricDetail[] {
  return getFabricDetailsForStyleFromRows(styleId, FABRIC_DETAIL_ROWS);
}

export function getFabricDetailsForStyleFromRows(
  styleId: string,
  rows: FabricDetail[]
): FabricDetail[] {
  return indexFabricDetails(rows)[normalizeStyleId(styleId)] ?? [];
}

export function attachFabricDetailsFromRows<T extends { id: string }>(
  styles: T[],
  rows: FabricDetail[]
): Array<T & { fabric_details?: FabricDetail[] }> {
  const detailsByStyle = indexFabricDetails(rows);
  return styles.map((style) => {
    const fabricDetails = detailsByStyle[normalizeStyleId(style.id)] ?? [];
    return fabricDetails.length > 0
      ? { ...style, fabric_details: fabricDetails }
      : style;
  });
}

export async function attachFabricDetails<T extends { id: string }>(
  styles: T[]
): Promise<Array<T & { fabric_details?: FabricDetail[] }>> {
  const rows = await fetchCurrentFabricDetails();
  return attachFabricDetailsFromRows(styles, rows);
}

async function fetchCurrentFabricDetails(): Promise<FabricDetail[]> {
  try {
    const response = await fetch("/api/fabric-details", { cache: "no-store" });
    if (!response.ok) return FABRIC_DETAIL_ROWS;
    const payload = (await response.json()) as FabricDetailsResponse;
    return Array.isArray(payload.rows) ? payload.rows : FABRIC_DETAIL_ROWS;
  } catch {
    return FABRIC_DETAIL_ROWS;
  }
}

function indexFabricDetails(rows: FabricDetail[]): Record<string, FabricDetail[]> {
  return rows.reduce<Record<string, FabricDetail[]>>((acc, detail) => {
    const key = normalizeStyleId(detail.styleId);
    if (!acc[key]) acc[key] = [];
    acc[key].push(detail);
    return acc;
  }, {});
}

function normalizeStyleId(styleId: string): string {
  return styleId.trim().toUpperCase();
}
