import type { Style } from "./types";

const COLLECTION = "SP27-TALBOTS-OUTLET";

export const MOCK_STYLES: Style[] = [
  {
    id: "HDW127182",
    collection: COLLECTION,
    division: "Knit Top",
    fabric_no: "FL25112486",
    contents: "100% Cotton",
    construction: "Pointelle",
    weight: "300 G/M\u00B2",
    finishing: "",
    designed_by: "Hansoll",
    image_url: "https://placeholder.supabase.co/storage/v1/object/public/style-images/HDW127182.jpg",
    images: ["https://placeholder.supabase.co/storage/v1/object/public/style-images/HDW127182.jpg"],
    fabric_suggestion: {
      fabric_no: "FL25082331 Thermal",
      contents: "65/32/3 Cotton/Polyester/Spandex",
      weight: "240 G/M\u00B2",
    },
  },
  {
    id: "HDW127079",
    collection: COLLECTION,
    division: "Knit Top",
    fabric_no: "HS-1027-H",
    contents: "100% Cotton",
    construction: "Single Jersey",
    weight: "265 G/M\u00B2",
    finishing: "",
    designed_by: "Hansoll",
    image_url: "https://placeholder.supabase.co/storage/v1/object/public/style-images/HDW127079.jpg",
    images: ["https://placeholder.supabase.co/storage/v1/object/public/style-images/HDW127079.jpg"],
    fabric_suggestion: {
      fabric_no: "FL25062903 Single Jersey",
      contents: "100% Cotton",
      weight: "230 G/M\u00B2",
    },
  },
  {
    id: "HDW126208",
    collection: COLLECTION,
    division: "Knit Top",
    fabric_no: "FL24022159",
    contents: "71/15/14 Cotton/Modal/Polyester",
    construction: "French Terry",
    weight: "250 G/M\u00B2",
    finishing: "",
    designed_by: "Hansoll",
    image_url: "https://placeholder.supabase.co/storage/v1/object/public/style-images/HDW126208.jpg",
    images: ["https://placeholder.supabase.co/storage/v1/object/public/style-images/HDW126208.jpg"],
    fabric_suggestion: {
      fabric_no: "FL22110006 French Terry",
      contents: "58/39/3 Cotton/Modal/Span",
      weight: "195 G/M\u00B2",
    },
  },
  {
    id: "HMW320041",
    collection: COLLECTION,
    division: "Knit Top",
    fabric_no: "",
    contents: "63/34/3 Cotton/Polyester/Spandex",
    construction: "Single Jacquard",
    weight: "224 G/M\u00B2",
    finishing: "",
    designed_by: "Bershka",
    image_url: "https://placeholder.supabase.co/storage/v1/object/public/style-images/HMW320041.jpg",
    images: ["https://placeholder.supabase.co/storage/v1/object/public/style-images/HMW320041.jpg"],
    fabric_suggestion: {
      fabric_no: "FL25082416 Quilt Jacquard",
      contents: "83/15/2 Polyester/Rayon/Spandex",
      weight: "300 G/M\u00B2",
    },
  },
  {
    id: "HMW326235",
    collection: COLLECTION,
    division: "Knit Top",
    fabric_no: "",
    contents: "100% Rayon",
    construction: "Quilt Jacquard",
    weight: "280 G/M\u00B2",
    finishing: "",
    designed_by: "Lou&Grey",
    image_url: "https://placeholder.supabase.co/storage/v1/object/public/style-images/HMW326235.jpg",
    images: ["https://placeholder.supabase.co/storage/v1/object/public/style-images/HMW326235.jpg"],
    fabric_suggestion: {
      fabric_no: "FL25082416 Quilt Jacquard",
      contents: "83/15/2 Polyester/Rayon/Spandex",
      weight: "300 G/M\u00B2",
    },
  },
];
